### ISSUE TITLE
Detect command-line operation

### ISSUE THREAD

**Issue by deltafactory** [littlebizzy/force-https#2]
As reported in https://wordpress.org/support/topic/undefined-index-http_host-4/

I suggest adding something like the following to the method checkSSLRedirect in core/core.php:

```
if ( php_sapi_name() === 'cli' ) {
    return false;
}
```

**Comment by jessuppi** [comment]
Fixed in version 1.3.0 thanks!

https://github.com/littlebizzy/force-https/tree/1.3.0
