### ISSUE TITLE
Add <source> to content filters

### ISSUE THREAD

**Issue by deltafactory** [littlebizzy/force-https#7]
Support locally hosted audio/video element sources. Similar to the existing support for <script> tags at https://github.com/littlebizzy/force-https/blob/1.2.1/core/filters.php#L77

`'#<(source)[\s|\t][^>]*?src=[\'"]\K(http://|//)[^\'"]+#i',		// source elements`

**Comment by jessuppi** [comment]
This should now be fixed in version 1.4.0:

https://github.com/littlebizzy/force-https/tree/1.4.0
